name: 手动构建

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      seam_version:
        description: 'seam 版本'
        required: true
        default: 'latest'

jobs:
  check:
    runs-on: ubuntu-latest
    name: 手动构建

    steps:
    - name: 获取 versions
      id: getVersions
      run: |
        if [ ${{ github.event.inputs.seam_version }} == "latest" ]
        then
          seam_version="$((curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Borber/seam/releases/latest) \
          | jq -r '.tag_name')"
        else
          seam_version=${{ github.event.inputs.seam_version }}
        fi
        echo "seam_version=${seam_version}" >> $GITHUB_OUTPUT
        echo "seam_version: $seam_version"

    - name: 触发构建
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: manual-build
        client-payload: '{"seam_version": "${{ steps.getVersions.outputs.seam_version }}"}'
        
    - name: 删除旧的 workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4