name: 手动构建

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      seam_version:
        description: 'seam cli 版本'
        required: true
        default: '0.1.34'

jobs:
  check:
    runs-on: ubuntu-latest
    name: 手动构建

    steps:
    - name: 触发构建
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: manual-build
        client-payload: '{"seam_version": "${{ github.event.inputs.seam_version }}"}'
        
    - name: 删除旧的 workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4