name: 自动构建

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */24 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    name: 自动构建

    steps:
    - name: 检查是否需要更新
      id: compareVersions
      run: |
        seam_version = "$((curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Borber/seam/releases/latest) \
          | jq -r '.tag_name')"

        proxy_release_id = "$((curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/zhuxiaole/docker-live-stream-proxy/releases/latest) \
          | jq -r '.id')"

        proxy_release_body = "$((curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/zhuxiaole/docker-live-stream-proxy/releases/${proxy_release_id}) \
          | jq -r '.body')"
        proxy_seam_version = (${proxy_release_body//:/ })[1]

        if [ $seam_version == $proxy_seam_version ]
        then
          update='false'
        else
          update='true'
        fi
        echo "seam_version=${seam_version}" >> $GITHUB_OUTPUT
        echo "update=${update}" >> $GITHUB_OUTPUT
        echo "是否更新: $update | 最新seam版本: $seam_version"

    - name: 触发构建
      if: steps.compareVersions.outputs.update == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: schedule-build
        client-payload: '{"seam_version": "${{ steps.compareVersions.outputs.seam_version }}"}'
        
    - name: 删除旧的 workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4