name: 自动构建

env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: 0 */24 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    name: 自动构建

    steps:
    - name: 获取最新 versions
      id: latestVersions
      run: |
        seam_version="$((curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Borber/seam/releases/latest) \
          | jq -r '.tag_name')"

        echo "seam_version=${seam_version}" >> $GITHUB_OUTPUT
        echo "最新seam版本: $seam_version"

    - name: 触发构建
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: schedule-build
        client-payload: '{"seam_version": "${{ steps.latestVersions.outputs.seam_version }}"}'
        
    - name: 删除旧的 workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4